const properties = [
  {
    id: "CSS Lists Module Level 3",
    children: [
      { id: "list-style-image" },
      { id: "list-style-type" },
      { id: "list-style-position" },
      { id: "list-style" },
      { id: "marker-side" },
      { id: "counter-reset" },
      { id: "counter-increment" },
      { id: "counter-set" },
    ],
  },
  {
    id: "CSS Inline Layout Module Level 3",
    children: [
      { id: "dominant-baseline" },
      { id: "vertical-align" },
      { id: "baseline-source" },
      { id: "alignment-baseline" },
      { id: "baseline-shift" },
      { id: "line-height" },
      { id: "text-edge" },
      { id: "leading-trim" },
      { id: "inline-sizing" },
      { id: "initial-letter" },
      { id: "initial-letter-align" },
      { id: "initial-letter-wrap" },
    ],
  },
  {
    id: "CSS Containment Module Level 2",
    children: [{ id: "contain" }, { id: "content-visibility" }],
  },
  {
    id: "CSS Overflow Module Level 3",
    children: [
      { id: "overflow-x" },
      { id: "overflow-y" },
      { id: "overflow" },
      { id: "overflow-clip-margin" },
      { id: "overflow-inline" },
      { id: "overflow-block" },
      { id: "text-overflow" },
      { id: "block-ellipsis" },
      { id: "line-clamp" },
      { id: "max-lines" },
      { id: "continue" },
    ],
  },
  {
    id: "CSS Box Sizing Module Level 4",
    children: [{ id: "aspect-ratio" }, { id: "contain-intrinsic-size" }],
  },
  {
    id: "CSS Positioned Layout Module Level 3",
    children: [
      { id: "position" },
      { id: "top" },
      { id: "right" },
      { id: "bottom" },
      { id: "left" },
      { id: "inset-block-start" },
      { id: "inset-inline-start" },
      { id: "inset-block-end" },
      { id: "inset-inline-end" },
      { id: "inset-block" },
      { id: "inset-inline" },
      { id: "inset" },
    ],
  },
  { id: "CSS Display Module Level 3", children: [{ id: "display" }] },
  {
    id: "CSS Text Decoration Module Level 4",
    children: [
      { id: "text-decoration-line" },
      { id: "text-decoration-style" },
      { id: "text-decoration-color" },
      { id: "text-decoration-thickness" },
      { id: "text-decoration" },
      { id: "text-underline-position" },
      { id: "text-underline-offset" },
      { id: "text-decoration-skip" },
      { id: "text-decoration-skip-self" },
      { id: "text-decoration-skip-box" },
      { id: "text-decoration-skip-inset" },
      { id: "text-decoration-skip-spaces" },
      { id: "text-decoration-skip-ink" },
      { id: "text-emphasis-style" },
      { id: "text-emphasis-color" },
      { id: "text-emphasis" },
      { id: "text-emphasis-position" },
      { id: "text-emphasis-skip" },
      { id: "text-shadow" },
    ],
  },
  {
    id: "CSS Ruby Layout Module Level 1",
    children: [
      { id: "ruby-position" },
      { id: "ruby-merge" },
      { id: "ruby-align" },
      { id: "ruby-overhang" },
    ],
  },
  {
    id: "CSS Text Module Level 3",
    children: [
      { id: "text-transform" },
      { id: "white-space" },
      { id: "tab-size" },
      { id: "word-break" },
      { id: "line-break" },
      { id: "hyphens" },
      { id: "overflow-wrap" },
      { id: "word-wrap" },
      { id: "text-align" },
      { id: "text-align-all" },
      { id: "text-align-last" },
      { id: "text-justify" },
      { id: "word-spacing" },
      { id: "letter-spacing" },
      { id: "text-indent" },
      { id: "hanging-punctuation" },
    ],
  },
  {
    id: "CSS Box Model Module Level 3",
    children: [
      { id: "margin-top" },
      { id: "margin-right" },
      { id: "margin-bottom" },
      { id: "margin-left" },
      { id: "margin" },
      { id: "padding-top" },
      { id: "padding-right" },
      { id: "padding-bottom" },
      { id: "padding-left" },
      { id: "padding" },
    ],
  },
  {
    id: "CSS Box Model Module Level 4",
    children: [
      { id: "margin-top" },
      { id: "margin-right" },
      { id: "margin-bottom" },
      { id: "margin-left" },
      { id: "margin" },
      { id: "margin-trim" },
      { id: "padding-top" },
      { id: "padding-right" },
      { id: "padding-bottom" },
      { id: "padding-left" },
      { id: "padding" },
    ],
  },
  {
    id: "CSS Box Alignment Module Level 3",
    children: [
      { id: "align-content" },
      { id: "justify-content" },
      { id: "place-content" },
      { id: "justify-self" },
      { id: "align-self" },
      { id: "place-self" },
      { id: "justify-items" },
      { id: "align-items" },
      { id: "place-items" },
      { id: "row-gap" },
      { id: "column-gap" },
      { id: "gap" },
    ],
  },
  {
    id: "CSS Color Adjustment Module Level 1",
    children: [
      { id: "color-scheme" },
      { id: "forced-color-adjust" },
      { id: "color-adjust" },
    ],
  },
  {
    id: "CSS Transforms Module Level 2",
    children: [
      { id: "translate" },
      { id: "rotate" },
      { id: "scale" },
      { id: "transform-style" },
      { id: "perspective" },
      { id: "perspective-origin" },
      { id: "backface-visibility" },
    ],
  },
  {
    id: "CSS Scroll Anchoring Module Level 1",
    children: [{ id: "overflow-anchor" }],
  },
  {
    id: "CSS Basic User Interface Module Level 4",
    children: [
      { id: "outline" },
      { id: "outline-width" },
      { id: "outline-style" },
      { id: "outline-color" },
      { id: "outline-offset" },
      { id: "resize" },
      { id: "cursor" },
      { id: "caret-color" },
      { id: "caret-shape" },
      { id: "caret" },
      { id: "nav-up" },
      { id: "nav-right" },
      { id: "nav-down" },
      { id: "nav-left" },
      { id: "user-select" },
      { id: "appearance" },
    ],
  },
  {
    id: "CSS Writing Modes Level 3",
    children: [
      { id: "direction" },
      { id: "unicode-bidi" },
      { id: "writing-mode" },
      { id: "text-orientation" },
      { id: "glyph-orientation-vertical" },
      { id: "text-combine-upright" },
    ],
  },
  {
    id: "CSS Spatial Navigation Level 1",
    children: [
      { id: "spatial-navigation-contain" },
      { id: "spatial-navigation-action" },
      { id: "spatial-navigation-function" },
    ],
  },
  { id: "CSS Containment Module Level 1", children: [{ id: "contain" }] },
  {
    id: "CSS Text Module Level 4",
    children: [
      { id: "word-boundary-detection" },
      { id: "word-boundary-expansion" },
      { id: "text-space-collapse" },
      { id: "text-space-trim" },
      { id: "text-wrap" },
      { id: "wrap-before" },
      { id: "wrap-after" },
      { id: "wrap-inside" },
      { id: "white-space" },
      { id: "hyphenate-character" },
      { id: "hyphenate-limit-zone" },
      { id: "hyphenate-limit-chars" },
      { id: "hyphenate-limit-lines" },
      { id: "hyphenate-limit-last" },
      { id: "text-group-align" },
      { id: "line-padding" },
      { id: "text-spacing" },
    ],
  },
  {
    id: "CSS Fonts Module Level 4",
    children: [
      { id: "font-family" },
      { id: "font-weight" },
      { id: "font-stretch" },
      { id: "font-style" },
      { id: "font-size" },
      { id: "font-size-adjust" },
      { id: "font" },
      { id: "font-synthesis-weight" },
      { id: "font-synthesis-style" },
      { id: "font-synthesis-small-caps" },
      { id: "font-synthesis" },
      { id: "font-kerning" },
      { id: "font-variant-ligatures" },
      { id: "font-variant-position" },
      { id: "font-variant-caps" },
      { id: "font-variant-numeric" },
      { id: "font-variant-alternates" },
      { id: "font-variant-east-asian" },
      { id: "font-variant" },
      { id: "font-feature-settings" },
      { id: "font-language-override" },
      { id: "font-optical-sizing" },
      { id: "font-variation-settings" },
      { id: "font-palette" },
      { id: "font-variant-emoji" },
    ],
  },
  {
    id: "CSS Color Module Level 4",
    children: [{ id: "color" }, { id: "opacity" }],
  },
  {
    id: "CSS Multi-column Layout Module Level 1",
    children: [
      { id: "column-width" },
      { id: "column-count" },
      { id: "columns" },
      { id: "column-rule-color" },
      { id: "column-rule-style" },
      { id: "column-rule-width" },
      { id: "column-rule" },
      { id: "column-span" },
      { id: "column-fill" },
    ],
  },
  {
    id: "CSS Images Module Level 3",
    children: [
      { id: "object-fit" },
      { id: "object-position" },
      { id: "image-orientation" },
      { id: "image-rendering" },
    ],
  },
  {
    id: "CSS Text Decoration Module Level 3",
    children: [
      { id: "text-decoration-line" },
      { id: "text-decoration-style" },
      { id: "text-decoration-color" },
      { id: "text-decoration" },
      { id: "text-underline-position" },
      { id: "text-emphasis-style" },
      { id: "text-emphasis-color" },
      { id: "text-emphasis" },
      { id: "text-emphasis-position" },
      { id: "text-shadow" },
    ],
  },
  {
    id: "CSS Generated Content Module Level 3",
    children: [
      { id: "content" },
      { id: "quotes" },
      { id: "string-set" },
      { id: "bookmark-level" },
      { id: "bookmark-label" },
      { id: "bookmark-state" },
    ],
  },
  {
    id: "CSS Writing Modes Level 4",
    children: [
      { id: "direction" },
      { id: "unicode-bidi" },
      { id: "writing-mode" },
      { id: "text-orientation" },
      { id: "glyph-orientation-vertical" },
      { id: "text-combine-upright" },
    ],
  },
  {
    id: "CSS Table Module Level 3",
    children: [
      { id: "table-layout" },
      { id: "border-collapse" },
      { id: "border-spacing" },
      { id: "caption-side" },
      { id: "empty-cells" },
    ],
  },
  {
    id: "CSS Overscroll Behavior Module Level 1",
    children: [
      { id: "overscroll-behavior" },
      { id: "overscroll-behavior-x" },
      { id: "overscroll-behavior-y" },
      { id: "overscroll-behavior-inline" },
      { id: "overscroll-behavior-block" },
    ],
  },
  {
    id: "CSS Intrinsic & Extrinsic Sizing Module Level 3",
    children: [
      { id: "width" },
      { id: "height" },
      { id: "min-width" },
      { id: "min-height" },
      { id: "max-width" },
      { id: "max-height" },
      { id: "box-sizing" },
    ],
  },
  {
    id: "CSS Scroll Snap Module Level 1",
    children: [
      { id: "scroll-snap-type" },
      { id: "scroll-padding" },
      { id: "scroll-margin" },
      { id: "scroll-snap-align" },
      { id: "scroll-snap-stop" },
      { id: "scroll-padding-top" },
      { id: "scroll-padding-right" },
      { id: "scroll-padding-bottom" },
      { id: "scroll-padding-left" },
      { id: "scroll-padding-inline-start" },
      { id: "scroll-padding-block-start" },
      { id: "scroll-padding-inline-end" },
      { id: "scroll-padding-block-end" },
      { id: "scroll-padding-block" },
      { id: "scroll-padding-inline" },
      { id: "scroll-margin-top" },
      { id: "scroll-margin-right" },
      { id: "scroll-margin-bottom" },
      { id: "scroll-margin-left" },
      { id: "scroll-margin-block-start" },
      { id: "scroll-margin-inline-start" },
      { id: "scroll-margin-block-end" },
      { id: "scroll-margin-inline-end" },
      { id: "scroll-margin-block" },
      { id: "scroll-margin-inline" },
    ],
  },
  {
    id: "CSS Transforms Module Level 1",
    children: [
      { id: "transform" },
      { id: "transform-origin" },
      { id: "transform-box" },
    ],
  },
  {
    id: "Motion Path Module Level 1",
    children: [
      { id: "offset-path" },
      { id: "offset-distance" },
      { id: "offset-position" },
      { id: "offset-anchor" },
      { id: "offset-rotate" },
      { id: "offset" },
    ],
  },
  {
    id: "Filter Effects Module Level 1",
    children: [
      { id: "filter" },
      { id: "flood-color" },
      { id: "flood-opacity" },
      { id: "color-interpolation-filters" },
      { id: "lighting-color" },
    ],
  },
  {
    id: "CSS Fragmentation Module Level 4",
    children: [
      { id: "break-before" },
      { id: "break-after" },
      { id: "break-inside" },
      { id: "orphans" },
      { id: "widows" },
      { id: "margin-break" },
      { id: "box-decoration-break" },
    ],
  },
  {
    id: "CSS Fragmentation Module Level 3",
    children: [
      { id: "break-before" },
      { id: "break-after" },
      { id: "break-inside" },
      { id: "orphans" },
      { id: "widows" },
      { id: "box-decoration-break" },
    ],
  },
  {
    id: "CSS Flexible Box Layout Module Level 1",
    children: [
      { id: "flex-direction" },
      { id: "flex-wrap" },
      { id: "flex-flow" },
      { id: "order" },
      { id: "flex" },
      { id: "flex-grow" },
      { id: "flex-shrink" },
      { id: "flex-basis" },
      { id: "justify-content" },
      { id: "align-items" },
      { id: "align-self" },
      { id: "align-content" },
    ],
  },
  { id: "CSS Paged Media Module Level 3", children: [{ id: "page" }] },
  {
    id: "CSS Transitions",
    children: [
      { id: "transition-property" },
      { id: "transition-duration" },
      { id: "transition-timing-function" },
      { id: "transition-delay" },
      { id: "transition" },
    ],
  },
  {
    id: "CSS Animations Level 1",
    children: [
      { id: "animation-name" },
      { id: "animation-duration" },
      { id: "animation-timing-function" },
      { id: "animation-iteration-count" },
      { id: "animation-direction" },
      { id: "animation-play-state" },
      { id: "animation-delay" },
      { id: "animation-fill-mode" },
      { id: "animation" },
    ],
  },
  {
    id: "CSS Scrollbars Module Level 1",
    children: [{ id: "scrollbar-color" }, { id: "scrollbar-width" }],
  },
  {
    id: "CSS Cascading and Inheritance Level 3",
    children: [{ id: "all" }],
  },
  {
    id: "CSS Cascading and Inheritance Level 4",
    children: [{ id: "all" }],
  },
  {
    id: "CSS Logical Properties and Values Level 1",
    children: [
      { id: "block-size" },
      { id: "inline-size" },
      { id: "min-block-size" },
      { id: "min-inline-size" },
      { id: "max-block-size" },
      { id: "max-inline-size" },
      { id: "margin-block-start" },
      { id: "margin-block-end" },
      { id: "margin-inline-start" },
      { id: "margin-inline-end" },
      { id: "margin-block" },
      { id: "margin-inline" },
      { id: "inset-block-start" },
      { id: "inset-block-end" },
      { id: "inset-inline-start" },
      { id: "inset-inline-end" },
      { id: "inset-block" },
      { id: "inset-inline" },
      { id: "inset" },
      { id: "padding-block-start" },
      { id: "padding-block-end" },
      { id: "padding-inline-start" },
      { id: "padding-inline-end" },
      { id: "padding-block" },
      { id: "padding-inline" },
      { id: "border-block-start-width" },
      { id: "border-block-end-width" },
      { id: "border-inline-start-width" },
      { id: "border-inline-end-width" },
      { id: "border-block-width" },
      { id: "border-inline-width" },
      { id: "border-block-start-style" },
      { id: "border-block-end-style" },
      { id: "border-inline-start-style" },
      { id: "border-inline-end-style" },
      { id: "border-block-style" },
      { id: "border-inline-style" },
      { id: "border-block-start-color" },
      { id: "border-block-end-color" },
      { id: "border-inline-start-color" },
      { id: "border-inline-end-color" },
      { id: "border-block-color" },
      { id: "border-inline-color" },
      { id: "border-block-start" },
      { id: "border-block-end" },
      { id: "border-inline-start" },
      { id: "border-inline-end" },
      { id: "border-block" },
      { id: "border-inline" },
      { id: "border-start-start-radius" },
      { id: "border-start-end-radius" },
      { id: "border-end-start-radius" },
      { id: "border-end-end-radius" },
    ],
  },
  {
    id: "CSS Basic User Interface Module Level 3 (CSS3 UI)",
    children: [
      { id: "box-sizing" },
      { id: "outline" },
      { id: "outline-width" },
      { id: "outline-style" },
      { id: "outline-color" },
      { id: "outline-offset" },
      { id: "resize" },
      { id: "text-overflow" },
      { id: "cursor" },
      { id: "caret-color" },
    ],
  },
  {
    id: "CSS Grid Layout Module Level 1",
    children: [
      { id: "grid-template-columns" },
      { id: "grid-template-rows" },
      { id: "grid-template-areas" },
      { id: "grid-template" },
      { id: "grid-auto-columns" },
      { id: "grid-auto-rows" },
      { id: "grid-auto-flow" },
      { id: "grid" },
      { id: "grid-row-start" },
      { id: "grid-column-start" },
      { id: "grid-row-end" },
      { id: "grid-column-end" },
      { id: "grid-row" },
      { id: "grid-column" },
      { id: "grid-area" },
    ],
  },
  {
    id: "CSS Backgrounds and Borders Module Level 3",
    children: [
      { id: "background-color" },
      { id: "background-image" },
      { id: "background-repeat" },
      { id: "background-attachment" },
      { id: "background-position" },
      { id: "background-clip" },
      { id: "background-origin" },
      { id: "background-size" },
      { id: "background" },
      { id: "border-top-color" },
      { id: "border-right-color" },
      { id: "border-bottom-color" },
      { id: "border-left-color" },
      { id: "border-color" },
      { id: "border-top-style" },
      { id: "border-right-style" },
      { id: "border-bottom-style" },
      { id: "border-left-style" },
      { id: "border-style" },
      { id: "border-top-width" },
      { id: "border-right-width" },
      { id: "border-bottom-width" },
      { id: "border-left-width" },
      { id: "border-width" },
      { id: "border-top" },
      { id: "border-right" },
      { id: "border-bottom" },
      { id: "border-left" },
      { id: "border" },
      { id: "border-top-left-radius" },
      { id: "border-top-right-radius" },
      { id: "border-bottom-right-radius" },
      { id: "border-bottom-left-radius" },
      { id: "border-radius" },
      { id: "border-image-source" },
      { id: "border-image-slice" },
      { id: "border-image-width" },
      { id: "border-image-outset" },
      { id: "border-image-repeat" },
      { id: "border-image" },
      { id: "box-shadow" },
    ],
  },
  {
    id: "CSS Overflow Module Level 4",
    children: [
      { id: "scrollbar-gutter" },
      { id: "continue" },
      { id: "max-lines" },
    ],
  },
  {
    id: "CSS Fill and Stroke Module Level 3",
    children: [
      { id: "fill-rule" },
      { id: "fill-break" },
      { id: "fill-color" },
      { id: "fill-image" },
      { id: "fill-origin" },
      { id: "fill-position" },
      { id: "fill-size" },
      { id: "fill-repeat" },
      { id: "fill" },
      { id: "fill-opacity" },
      { id: "stroke-width" },
      { id: "stroke-align" },
      { id: "stroke-linecap" },
      { id: "stroke-linejoin" },
      { id: "stroke-miterlimit" },
      { id: "stroke-break" },
      { id: "stroke-dasharray" },
      { id: "stroke-dashoffset" },
      { id: "stroke-dash-corner" },
      { id: "stroke-dash-justify" },
      { id: "stroke-color" },
      { id: "stroke-image" },
      { id: "stroke-origin" },
      { id: "stroke-position" },
      { id: "stroke-size" },
      { id: "stroke-repeat" },
      { id: "stroke" },
      { id: "stroke-opacity" },
    ],
  },
  {
    id: "CSS Image Values and Replaced Content Module Level 4",
    children: [{ id: "image-resolution" }],
  },
  {
    id: "CSS Rhythmic Sizing",
    children: [
      { id: "line-height-step" },
      { id: "block-step-size" },
      { id: "block-step-insert" },
      { id: "block-step-align" },
      { id: "block-step-round" },
      { id: "block-step" },
    ],
  },
  {
    id: "CSS Round Display Level 1",
    children: [{ id: "shape-inside" }, { id: "border-boundary" }],
  },
  { id: "CSSOM View Module", children: [{ id: "scroll-behavior" }] },
  {
    id: "CSS Custom Properties for Cascading Variables Module Level 1",
    children: [{ id: "--*" }],
  },
  {
    id: "CSS Will Change Module Level 1",
    children: [{ id: "will-change" }],
  },
  {
    id: "CSS Page Floats",
    children: [
      { id: "float-reference" },
      { id: "float" },
      { id: "clear" },
      { id: "float-defer" },
      { id: "float-offset" },
    ],
  },
  {
    id: "Priorities for CSS from the Digital Publishing Interest Group",
    children: [
      { id: "hyphenate-patterns" },
      { id: "min-length-of-last-line" },
      { id: "merge-sequential-page-numbers" },
    ],
  },
  {
    id: "CSS Exclusions Module Level 1",
    children: [{ id: "wrap-flow" }, { id: "wrap-through" }],
  },
  {
    id: "Compositing and Blending Level 1",
    children: [
      { id: "mix-blend-mode" },
      { id: "isolation" },
      { id: "background-blend-mode" },
    ],
  },
  {
    id: "CSS Regions Module Level 1",
    children: [
      { id: "flow-into" },
      { id: "flow-from" },
      { id: "break-before" },
      { id: "break-after" },
      { id: "break-inside" },
      { id: "region-fragment" },
    ],
  },
  {
    id: "CSS Line Grid Module Level 1",
    children: [{ id: "line-grid" }, { id: "line-snap" }, { id: "box-snap" }],
  },
  {
    id: "CSS Masking Module Level 1",
    children: [
      { id: "clip-path" },
      { id: "clip-rule" },
      { id: "mask-image" },
      { id: "mask-mode" },
      { id: "mask-repeat" },
      { id: "mask-position" },
      { id: "mask-clip" },
      { id: "mask-origin" },
      { id: "mask-size" },
      { id: "mask-composite" },
      { id: "mask" },
      { id: "mask-border-source" },
      { id: "mask-border-mode" },
      { id: "mask-border-slice" },
      { id: "mask-border-width" },
      { id: "mask-border-outset" },
      { id: "mask-border-repeat" },
      { id: "mask-border" },
      { id: "mask-type" },
      { id: "clip" },
    ],
  },
  {
    id: "CSS Generated Content for Paged Media Module",
    children: [
      { id: "string-set" },
      { id: "running" },
      { id: "footnote-display" },
      { id: "footnote-policy" },
      { id: "bookmark-level" },
      { id: "bookmark-label" },
      { id: "bookmark-state" },
      { id: "running" },
    ],
  },
  {
    id: "CSS Shapes Module Level 1",
    children: [
      { id: "shape-outside" },
      { id: "shape-image-threshold" },
      { id: "shape-margin" },
    ],
  },
];
